### ISSUE TITLE
NDVI Example

### ISSUE THREAD

**Issue by emilyselwood** [SatelliteApplicationsCatapult/fulgurite#37]
Calculating NDVI is a very common eo operation.

We should have an example that shows how to do this.

**Comment by emilyselwood** [comment]
read image -> filter for just the bands we need -> pixelGroup -> perform calculation -> write result.

**Comment by ghost** [comment]
I am working on this.

**Comment by ghost** [comment]
The NDVI example has been completed. Please see #43.
